-- Tables alimentées mois par mois (DELETE du mois puis INSERT).
-- CREATE TABLE IF NOT EXISTS : la tâche peut être rejouée sans rien casser.

CREATE TABLE IF NOT EXISTS NYC_TAXI.INTERMEDIATE.INT_TRIPS__FLAGGED (
    vendor_key                    INTEGER,
    rate_code_key                 INTEGER,
    payment_type_key              INTEGER,
    pickup_zone_key               INTEGER,
    dropoff_zone_key              INTEGER,
    pickup_at                     TIMESTAMP_NTZ,
    dropoff_at                    TIMESTAMP_NTZ,
    passenger_count               INTEGER,
    trip_distance_miles           FLOAT,
    is_store_and_forward          BOOLEAN,
    fare_amount                   FLOAT,
    extra_amount                  FLOAT,
    mta_tax_amount                FLOAT,
    tip_amount                    FLOAT,
    tolls_amount                  FLOAT,
    improvement_surcharge_amount  FLOAT,
    congestion_surcharge_amount   FLOAT,
    airport_fee_amount            FLOAT,
    cbd_congestion_fee_amount     FLOAT,
    total_amount                  FLOAT,
    source_file                   VARCHAR,
    source_file_month             DATE,
    loaded_at                     TIMESTAMP_NTZ,
    trip_duration_min             FLOAT,
    rejection_reason              VARCHAR
)
COMMENT = 'Tous les trajets, avec la raison de rejet éventuelle (NULL = trajet valide)';

CREATE TABLE IF NOT EXISTS NYC_TAXI.INTERMEDIATE.INT_TRIPS__ENRICHED (
    trip_sk                       VARCHAR,
    vendor_key                    INTEGER,
    rate_code_key                 INTEGER,
    payment_type_key              INTEGER,
    pickup_zone_key               INTEGER,
    dropoff_zone_key              INTEGER,
    pickup_at                     TIMESTAMP_NTZ,
    dropoff_at                    TIMESTAMP_NTZ,
    pickup_date                   DATE,
    pickup_date_key               INTEGER,
    pickup_hour                   INTEGER,
    pickup_day_of_week_iso        INTEGER,
    is_weekend                    BOOLEAN,
    passenger_count               INTEGER,
    is_store_and_forward          BOOLEAN,
    trip_distance_miles           FLOAT,
    trip_duration_min             FLOAT,
    avg_speed_mph                 FLOAT,
    fare_amount                   FLOAT,
    extra_amount                  FLOAT,
    mta_tax_amount                FLOAT,
    tip_amount                    FLOAT,
    tolls_amount                  FLOAT,
    improvement_surcharge_amount  FLOAT,
    congestion_surcharge_amount   FLOAT,
    airport_fee_amount            FLOAT,
    cbd_congestion_fee_amount     FLOAT,
    total_amount                  FLOAT,
    tip_rate_pct                  FLOAT,
    source_file                   VARCHAR,
    source_file_month             DATE,
    loaded_at                     TIMESTAMP_NTZ
)
COMMENT = 'Trajets valides, dédoublonnés et enrichis (durée, vitesse, taux de pourboire)';

CREATE TABLE IF NOT EXISTS NYC_TAXI.MARTS.FCT_TRIPS (
    trip_sk              VARCHAR,
    pickup_date_key      INTEGER,
    pickup_zone_key      INTEGER,
    dropoff_zone_key     INTEGER,
    payment_type_key     INTEGER,
    rate_code_key        INTEGER,
    vendor_key           INTEGER,
    pickup_at            TIMESTAMP_NTZ,
    dropoff_at           TIMESTAMP_NTZ,
    pickup_date          DATE,
    pickup_hour          INTEGER,
    is_weekend           BOOLEAN,
    passenger_count      INTEGER,
    trip_distance_miles  FLOAT,
    trip_duration_min    FLOAT,
    avg_speed_mph        FLOAT,
    fare_amount          FLOAT,
    tip_amount           FLOAT,
    tolls_amount         FLOAT,
    surcharges_amount    FLOAT,
    total_amount         FLOAT,
    tip_rate_pct         FLOAT,
    source_file          VARCHAR,
    source_file_month    DATE,
    loaded_at            TIMESTAMP_NTZ
)
COMMENT = 'Table de faits : 1 ligne = 1 trajet valide';
